import type { Metadata } from 'next';
import { Golos_Text } from 'next/font/google';
import '@styles/globals.scss';
import { SITE_NAME } from '@/constants/seo';
import Providers from '@/components/Layouts/Providers';

const golosText = Golos_Text({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: SITE_NAME,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <Providers>
        <body className={`${golosText.className} antialiased`}>{children}</body>
      </Providers>
    </html>
  );
}
